### ISSUE TITLE
Incompatible with Essential Mod

### ISSUE THREAD

**Issue by SuperDZ555** [simply-kel/AlinLib#13]
Before, it worked perfectly fine with Essential Mod by SparkUniverse, but for some reason, Essential Mod doesn't load properly when combined with the latest release of this mod.

**Comment by kel-cu** [comment]
I am aware of this problem, although I do not like Essential, but I am trying to fix this problem.
Otherwise, I recommend you to stop using Essential: https://notessential.blurryface.xyz/

**Comment by kel-cu** [comment]
Fixed
