### ISSUE TITLE
Translation to Ukrainian | Перевод на украинский

### ISSUE THREAD

**Issue by StarmanMine142** [simply-kel/AlinLib#14]
Could you add the Ukrainian translation created by me?
Не могли бы вы добавить созданный мной украинский перевод?

[uk_ua.json](https://github.com/user-attachments/files/18059644/uk_ua.json)

**Comment by ImGRUI** [comment]
Создай пулл реквест тут и в waterplayer, тогда можно будет добавить

**Comment by StarmanMine142** [comment]
хорошо

**Comment by StarmanMine142** [comment]
Простите, но не могли бы вы объяснить как создать пулл реквест? У меня просто не получается

**Comment by ImGRUI** [comment]
Перекинь uk_ua.json сюда https://github.com/StarmanMine142/WaterPlayer/tree/v2.1/src/main/resources/assets/waterplayer/lang и затем нажми на кнопку contribute->Open Pull Request на главной странице твоего форка (скриншот для примера)
![image](https://github.com/user-attachments/assets/0e752eca-b0cb-4d22-bbba-58b0fdf86173)

**Comment by StarmanMine142** [comment]
![image](https://github.com/user-attachments/assets/4d45064e-94de-45a2-a1ef-2651fe6323cb)

у меня нету кнопки

**Comment by ImGRUI** [comment]
Потому что ты не закинул файл локализации.
Когда ты его закинешь - появится коммит, и с ним уже можно будет открыть.

**Comment by ImGRUI** [comment]
![image](https://github.com/user-attachments/assets/5ac26faf-5651-45f6-b615-7c6460afc146)

**Comment by StarmanMine142** [comment]
ну вроде создал пулл реквест

**Comment by StarmanMine142** [comment]
Waterplayer: https://github.com/kel-cu/WaterPlayer/compare/v2.1...StarmanMine142:WaterPlayer:patch-3
Alinlib: https://github.com/kel-cu/AlinLib/compare/v2.0...StarmanMine142:AlinLib:patch-1

**Comment by ImGRUI** [comment]
Это просто сравнение, тебе нужно нажать на эту кнопку
![image](https://github.com/user-attachments/assets/6ea2de11-1b06-4c0a-9705-1faa60c67133)

**Comment by StarmanMine142** [comment]
А теперь?
https://github.com/kel-cu/AlinLib/pull/15
https://github.com/kel-cu/WaterPlayer/pull/43

**Comment by ImGRUI** [comment]
Теперь всё верно.

**Comment by StarmanMine142** [comment]
Ура, большое спасибо за помощь!

**Comment by kel-cu** [comment]
Ещё раз спасибо за перевод)
